# Creating a Logistic regression to predict absenteeism 

# Import relevant libraries

In [1]:
import pandas as pd
import numpy as np

# Load the data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

# Create the targets

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteesim'] = targets

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteesim  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

# A comment on the targets

In [9]:
targets.sum()/targets.shape[0]

0.45571428571428574

# Dropping the 'Absenteeism Time in Hours' from the data table

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis = 1)

In [11]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive Absenteesim  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

In [12]:
data_with_targets is data_preprocessed # check whether the data in two tables are similar or not

False

# Select the inputs for the regression

- DataFrame.iloc[row indices,column indices] selects (slices) data by position when given rows and columns wanted 

In [13]:
data_with_targets.shape

(700, 15)

In [14]:
data_with_targets.iloc[:, 0:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [15]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [16]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

# Standardize the data

In [17]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()

In [18]:
# from sklearn.base import BaseEstimator, TransformerMixin
# from sklearn.preprocessing import StandardScaler

# class CustomScaler(BaseEstimator, TransformerMixin):
    
#     def __init__(self, columns, copy=True, with_mean=True, with_std=True):
#         self.scaler = StandardScaler(copy, with_mean, with_std)
#         self.columns = columns
#         self.mean_ = None
#         self.var_ = None
    
#     def fit(self, X, y= None):
#         self.scaler.fit(X[self.columns], y)
#         self.mean_ = np.mean(X[self.columns])
#         self.var_ = np.var(X[self.columns])
#         return self
    
#     def transform(self, X, y=None, copy=None):
#         init_col_order = X.columns
#         X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
#         X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
#         return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]
        

In [19]:
# unscaled_inputs.columns.values

In [20]:
# columns_to_scale = ['Month Value','Day of the week', 'Transportation Expense', 'Distance to Work',
#        'Age', 'Daily Work Load Average', 'Body Mass Index',
#        'Children', 'Pets']

In [21]:
#absenteeism_scaler = CustomScaler(columns_to_scale)

In [22]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [23]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [24]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [25]:
scaled_inputs.shape

(700, 14)

# Split the data into train and test and shuffle

# Import the relevant module

In [26]:
from sklearn.model_selection import train_test_split

# Split

In [27]:
train_test_split(scaled_inputs, targets)

[array([[ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
          0.88046927, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
         -0.01928035,  0.26848661],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          2.67996851, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297]]),
 array([[ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  0.26848661],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  0.26848661],
        ...,
        [-0.57735027, -0.09298136,  3.17979734, ..., -

In [28]:
X_train, X_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [29]:
print(X_train.shape, y_train.shape)

(560, 14) (560,)


In [30]:
print(X_test.shape, y_test.shape)

(140, 14) (140,)


# Logistic regression with sklearn

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

# Training the model

In [32]:
reg = LogisticRegression()

In [33]:
reg.fit(X_train, y_train)

LogisticRegression()

In [34]:
reg.score(X_train,y_train)

0.7839285714285714

## Manually check the accuracy

In [35]:
model_outputs = reg.predict(X_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [36]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [37]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [38]:
np.sum((model_outputs == y_train))

439

In [39]:
model_outputs.shape[0]

560

In [40]:
np.sum((model_outputs == y_train))/model_outputs.shape[0]

0.7839285714285714

# Finding the intercepts and coefficients

In [41]:
reg.intercept_

array([-0.22206736])

In [42]:
reg.coef_

array([[ 2.07601767,  0.33504757,  1.56162303,  1.32927434,  0.18793677,
        -0.07062253,  0.70639316, -0.03986811, -0.20089491, -0.00456366,
         0.31933564, -0.135508  ,  0.38172443, -0.3332426 ]])

In [43]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [44]:
feature_name = unscaled_inputs.columns.values

In [45]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                  Reason_1     2.076018
1                  Reason_2     0.335048
2                  Reason_3     1.561623
3                  Reason_4     1.329274
4               Month Value     0.187937
5           Day of the week    -0.070623
6    Transportation Expense     0.706393
7          Distance to Work    -0.039868
8                       Age    -0.200895
9   Daily Work Load Average    -0.004564
10          Body Mass Index     0.319336
11                Education    -0.135508
12                 Children     0.381724
13                     Pets    -0.333243

In [46]:
summary_table.index = summary_table.index + 1

In [47]:
summary_table.loc[0] = ['intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 intercept    -0.222067
1                  Reason_1     2.076018
2                  Reason_2     0.335048
3                  Reason_3     1.561623
4                  Reason_4     1.329274
5               Month Value     0.187937
6           Day of the week    -0.070623
7    Transportation Expense     0.706393
8          Distance to Work    -0.039868
9                       Age    -0.200895
10  Daily Work Load Average    -0.004564
11          Body Mass Index     0.319336
12                Education    -0.135508
13                 Children     0.381724
14                     Pets    -0.333243

# Interpretting the coefficients

In [48]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [49]:
summary_table.sort_values('Odds_ratio', ascending = False)

Feature name  Coefficient  Odds_ratio
1                  Reason_1     2.076018    7.972656
3                  Reason_3     1.561623    4.766551
4                  Reason_4     1.329274    3.778301
7    Transportation Expense     0.706393    2.026668
13                 Children     0.381724    1.464808
2                  Reason_2     0.335048    1.398007
11          Body Mass Index     0.319336    1.376213
5               Month Value     0.187937    1.206757
10  Daily Work Load Average    -0.004564    0.995447
8          Distance to Work    -0.039868    0.960916
6           Day of the week    -0.070623    0.931814
12                Education    -0.135508    0.873272
9                       Age    -0.200895    0.817998
0                 intercept    -0.222067    0.800861
14                     Pets    -0.333243    0.716596

- A feature is not particularly important:
    - if its coefficient is around 0
    - if its odd ratio is around 1

# Testing the model



In [50]:
reg.score(X_test,y_test)

0.7357142857142858

In [52]:
predicted_proba = reg.predict_proba(X_test)
predicted_proba

array([[0.73864865, 0.26135135],
       [0.58845661, 0.41154339],
       [0.36763564, 0.63236436],
       [0.81198089, 0.18801911],
       [0.0613996 , 0.9386004 ],
       [0.30742403, 0.69257597],
       [0.29538175, 0.70461825],
       [0.08106026, 0.91893974],
       [0.80435611, 0.19564389],
       [0.76038732, 0.23961268],
       [0.46271934, 0.53728066],
       [0.15484755, 0.84515245],
       [0.04619732, 0.95380268],
       [0.72991038, 0.27008962],
       [0.23140393, 0.76859607],
       [0.55130442, 0.44869558],
       [0.5292476 , 0.4707524 ],
       [0.55522744, 0.44477256],
       [0.38197963, 0.61802037],
       [0.02527634, 0.97472366],
       [0.69617984, 0.30382016],
       [0.80458387, 0.19541613],
       [0.37734902, 0.62265098],
       [0.40003074, 0.59996926],
       [0.18229161, 0.81770839],
       [0.76011784, 0.23988216],
       [0.47050402, 0.52949598],
       [0.88997625, 0.11002375],
       [0.13577639, 0.86422361],
       [0.7969686 , 0.2030314 ],
       [0.

In [54]:
predicted_proba[:,1]

array([0.26135135, 0.41154339, 0.63236436, 0.18801911, 0.9386004 ,
       0.69257597, 0.70461825, 0.91893974, 0.19564389, 0.23961268,
       0.53728066, 0.84515245, 0.95380268, 0.27008962, 0.76859607,
       0.44869558, 0.4707524 , 0.44477256, 0.61802037, 0.97472366,
       0.30382016, 0.19541613, 0.62265098, 0.59996926, 0.81770839,
       0.23988216, 0.52949598, 0.11002375, 0.86422361, 0.2030314 ,
       0.38454827, 0.70459151, 0.70138178, 0.56363893, 0.19541613,
       0.54256241, 0.20504956, 0.82072323, 0.44466019, 0.61108219,
       0.20908782, 0.40281153, 0.21373621, 0.09844091, 0.84224496,
       0.66612989, 0.71672931, 0.26982044, 0.20155736, 0.17070043,
       0.5733945 , 0.08298962, 0.67931742, 0.28630329, 0.87253409,
       0.48546569, 0.9325331 , 0.2462249 , 0.08169672, 0.08239341,
       0.72795552, 0.6695154 , 0.31201864, 0.86026294, 0.1838827 ,
       0.2596655 , 0.0131662 , 0.22029913, 0.8123649 , 0.31453865,
       0.20433741, 0.07128014, 0.93325923, 0.46319471, 0.65517

# save the model
- with the help pf pickle we save the model
- pickle is a python module used to convert a Python object into a character stream


In [57]:
import pickle

In [59]:
# pickle the model file
with open("model", "wb") as file:
    pickle.dump(reg, file)

In [60]:
# pickle the scaler file
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)